---
development:
  cloud_name: dvrunmtqp
  api_key: '335617397765561'
  api_secret: VAHGq6ATO0PgIxW1vbpMW2jgEI4
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dvrunmtqp
  api_key: '335617397765561'
  api_secret: VAHGq6ATO0PgIxW1vbpMW2jgEI4
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dvrunmtqp
  api_key: '335617397765561'
  api_secret: VAHGq6ATO0PgIxW1vbpMW2jgEI4
  enhance_image_tag: true
  static_image_support: false
